[package]
name = "LeetCode_66_0118"
version = "0.1.0"
authors = ["anray <anray1980@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
